spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gks}
    username: ${DB_USER:gks}
    password: ${DB_PASSWORD:gks}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

security:
  jwt:
    secret: ${JWT_SECRET:dGVzdHNlY3JldHRlc3RzZWNyZXR0ZXN0c2VjcmV0dGVzdA==}
    expiration-ms: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info
